import { defineStore } from 'pinia'

export interface StoreInfo {
	id: number;
	name: string;
	address: string;
	distance: any;
	business_hours?: string;
	longitude?: number;
	latitude?: number;
	phone?: string;
}

export const useAppStore = defineStore('app', {
	state: () => ({
		currentStore: null as StoreInfo | null,
		orderMode: 'self-pickup' as 'self-pickup' | 'delivery',
		orderTabIndex: 0
	}),
	actions: {
		setStore(store: StoreInfo) {
			// 确保赋值的是纯对象
			this.currentStore = {
				id: store.id,
				name: store.name,
				address: store.address,
				distance: store.distance,
				business_hours: store.business_hours,
				longitude: store.longitude,
				latitude: store.latitude,
				phone: store.phone
			} as StoreInfo
		},
		setOrderMode(mode: 'self-pickup' | 'delivery') {
			this.orderMode = mode
		},
		setOrderTabIndex(index: number) {
			this.orderTabIndex = index
		}
	}
})
